# Generated by Django 3.1.6 on 2021-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20210228_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friends_book_reader',
        ),
        migrations.AddField(
            model_name='book',
            name='book_reader',
            field=models.ManyToManyField(through='p_library.BookReader', to='p_library.Friend'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='p_library/book'),
        ),
    ]
